# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

 theme = "blowfish"
# baseURL = "https://your_domain.com/"
defaultContentLanguage = "en"
languageCode = "en"

[params]
<<<<<<< HEAD
  images = ['logo.png']

=======
<<<<<<< HEAD
  images = ['logo.png']
=======
  images = ['apple-touch-icon.png']
>>>>>>> main
>>>>>>> main

[permalinks]
  posts = "/:title"

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
paginate = 10
summaryLength = 0

buildDrafts = false
buildFuture = false

# googleAnalytics = "G-XXXXXXXXX"

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
